/*
 * This file is generated by jOOQ.
 */

package edu.java.domain.jooq.tables.records;

import edu.java.domain.jooq.tables.Questions;
import java.beans.ConstructorProperties;
import java.util.UUID;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class QuestionsRecord extends UpdatableRecordImpl<QuestionsRecord> implements Record3<Integer, UUID, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached QuestionsRecord
     */
    public QuestionsRecord() {
        super(Questions.QUESTIONS);
    }

    /**
     * Create a detached, initialised QuestionsRecord
     */
    @ConstructorProperties({"questionId", "linkId", "answerCount"})
    public QuestionsRecord(@Nullable Integer questionId, @Nullable UUID linkId, @NotNull Integer answerCount) {
        super(Questions.QUESTIONS);

        setQuestionId(questionId);
        setLinkId(linkId);
        setAnswerCount(answerCount);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised QuestionsRecord
     */
    public QuestionsRecord(edu.java.domain.jooq.tables.pojos.Questions value) {
        super(Questions.QUESTIONS);

        if (value != null) {
            setQuestionId(value.getQuestionId());
            setLinkId(value.getLinkId());
            setAnswerCount(value.getAnswerCount());
            resetChangedOnNotNull();
        }
    }

    /**
     * Getter for <code>QUESTIONS.QUESTION_ID</code>.
     */
    @Nullable
    public Integer getQuestionId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>QUESTIONS.QUESTION_ID</code>.
     */
    public void setQuestionId(@Nullable Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>QUESTIONS.LINK_ID</code>.
     */
    @Nullable
    public UUID getLinkId() {
        return (UUID) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>QUESTIONS.LINK_ID</code>.
     */
    public void setLinkId(@Nullable UUID value) {
        set(1, value);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>QUESTIONS.ANSWER_COUNT</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Integer getAnswerCount() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>QUESTIONS.ANSWER_COUNT</code>.
     */
    public void setAnswerCount(@NotNull Integer value) {
        set(2, value);
    }

    @Override
    @NotNull
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    @Override
    @NotNull
    public Row3<Integer, UUID, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row3<Integer, UUID, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Integer> field1() {
        return Questions.QUESTIONS.QUESTION_ID;
    }

    @Override
    @NotNull
    public Field<UUID> field2() {
        return Questions.QUESTIONS.LINK_ID;
    }

    @Override
    @NotNull
    public Field<Integer> field3() {
        return Questions.QUESTIONS.ANSWER_COUNT;
    }

    @Override
    @Nullable
    public Integer component1() {
        return getQuestionId();
    }

    @Override
    @Nullable
    public UUID component2() {
        return getLinkId();
    }

    @Override
    @NotNull
    public Integer component3() {
        return getAnswerCount();
    }

    @Override
    @Nullable
    public Integer value1() {
        return getQuestionId();
    }

    @Override
    @Nullable
    public UUID value2() {
        return getLinkId();
    }

    @Override
    @NotNull
    public Integer value3() {
        return getAnswerCount();
    }

    @Override
    @NotNull
    public QuestionsRecord value1(@Nullable Integer value) {
        setQuestionId(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public QuestionsRecord value2(@Nullable UUID value) {
        setLinkId(value);
        return this;
    }

    @Override
    @NotNull
    public QuestionsRecord value3(@NotNull Integer value) {
        setAnswerCount(value);
        return this;
    }

    @Override
    @NotNull
    public QuestionsRecord values(@Nullable Integer value1, @Nullable UUID value2, @NotNull Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }
}
