app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 3600s

  retry-properties:
    attempts: 10
    backoff: 2s
    backoff-strategy: linear
    retry-status-codes:
      - 500
      - 502
      - 503
      - 404

  rate-limit-property:
    delay-refill: 30s
    limit: 100
    refill-limit: 20

  database-access-type: jpa

client:
  stackoverflow-properties:
    domain: stackoverflow.com
    api-url: https://api.stackexchange.com
    questions: /questions/%d?site=stackoverflow
  github-properties:
    domain: github.com
    api-url: https://api.github.com
    repos: /repos/%s/%s
  bot-properties:
    url: http://localhost:8090
  database-access-type: jooq

spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  api-docs:
    enabled: true

swagger-ui:
  path: /swagger-ui
