app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 3600s

  retry-properties:
    attempts: 10
    backoff: 2s
    backoff-strategy: linear
    retry-status-codes:
      - 500
      - 502
      - 503
      - 404

  rate-limit-property:
    delay-refill: 30s
    limit: 100
    refill-limit: 20

  kafka-properties:
    topic:
      name: topic1
      partitions-num: 10
      replicas-num: 1

  stackoverflow-properties:
    domain: stackoverflow.com
    api-url: https://api.stackexchange.com
    questions: /questions/%d?site=stackoverflow
  github-properties:
    domain: github.com
    api-url: https://api.github.com
    repos: /repos/%s/%s
  bot-properties:
    url: ${BOT_URL}
  database-access-type: jpa
  is-use-queue: true

spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
  kafka:
    consumer:
      auto-offset-reset: earliest
    bootstrapServers: ${KAFKA_BOOTSTRAP_SERVERS}

management:
  server:
    port: ${MANAGEMENT_PORT}
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
      base-path: /
      path-mapping:
        prometheus: /metrics
  metrics:
    tags:
      application: ${spring.application.name}

server:
  port: ${SERVER_PORT}

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui
