app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
  stackoverflow-properties:
    base-url: https://api.stackexchange.com
    url: /questions/%d?site=stackoverflow
  github-properties:
    base-url: https://api.github.com
    url: /repos/%s/%s
  bot-properties:
    url: http://localhost:8090

spring:
  application:
    name: scrapper

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  api-docs:
    enabled: true

swagger-ui:
  path: /swagger-ui
