app:
  telegram-token: ${TELEGRAM_API_KEY}
  scrapper-properties:
    chat:
    links:
    tg-chat-id:
    url: localhost:8080
spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  api-docs:
    enabled: true

swagger-ui:
  path: /swagger-ui
