/*
 * This file is generated by jOOQ.
 */

package edu.java.domain.jooq.tables;

import edu.java.domain.jooq.DefaultSchema;
import edu.java.domain.jooq.Keys;
import edu.java.domain.jooq.tables.records.ChatLinkRelationRecord;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class ChatLinkRelation extends TableImpl<ChatLinkRelationRecord> {

    /**
     * The reference instance of <code>CHAT_LINK_RELATION</code>
     */
    public static final ChatLinkRelation CHAT_LINK_RELATION = new ChatLinkRelation();
    private static final long serialVersionUID = 1L;
    /**
     * The column <code>CHAT_LINK_RELATION.CHAT_ID</code>.
     */
    public final TableField<ChatLinkRelationRecord, Long> CHAT_ID =
        createField(DSL.name("CHAT_ID"), SQLDataType.BIGINT.nullable(false), this, "");
    /**
     * The column <code>CHAT_LINK_RELATION.LINK_ID</code>.
     */
    public final TableField<ChatLinkRelationRecord, UUID> LINK_ID =
        createField(DSL.name("LINK_ID"), SQLDataType.UUID.nullable(false), this, "");
    private transient Chats _chats;
    private transient Links _links;

    private ChatLinkRelation(Name alias, Table<ChatLinkRelationRecord> aliased) {
        this(alias, aliased, null);
    }

    private ChatLinkRelation(Name alias, Table<ChatLinkRelationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>CHAT_LINK_RELATION</code> table reference
     */
    public ChatLinkRelation(String alias) {
        this(DSL.name(alias), CHAT_LINK_RELATION);
    }

    /**
     * Create an aliased <code>CHAT_LINK_RELATION</code> table reference
     */
    public ChatLinkRelation(Name alias) {
        this(alias, CHAT_LINK_RELATION);
    }

    /**
     * Create a <code>CHAT_LINK_RELATION</code> table reference
     */
    public ChatLinkRelation() {
        this(DSL.name("CHAT_LINK_RELATION"), null);
    }

    public <O extends Record> ChatLinkRelation(Table<O> child, ForeignKey<O, ChatLinkRelationRecord> key) {
        super(child, key, CHAT_LINK_RELATION);
    }

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<ChatLinkRelationRecord> getRecordType() {
        return ChatLinkRelationRecord.class;
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public UniqueKey<ChatLinkRelationRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_B;
    }

    @Override
    @NotNull
    public List<ForeignKey<ChatLinkRelationRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_B8, Keys.CONSTRAINT_B80);
    }

    /**
     * Get the implicit join path to the <code>PUBLIC.CHATS</code> table.
     */
    public Chats chats() {
        if (_chats == null) {
            _chats = new Chats(this, Keys.CONSTRAINT_B8);
        }

        return _chats;
    }

    /**
     * Get the implicit join path to the <code>PUBLIC.LINKS</code> table.
     */
    public Links links() {
        if (_links == null) {
            _links = new Links(this, Keys.CONSTRAINT_B80);
        }

        return _links;
    }

    @Override
    @NotNull
    public ChatLinkRelation as(String alias) {
        return new ChatLinkRelation(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public ChatLinkRelation as(Name alias) {
        return new ChatLinkRelation(alias, this);
    }

    @Override
    @NotNull
    public ChatLinkRelation as(Table<?> alias) {
        return new ChatLinkRelation(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public ChatLinkRelation rename(String name) {
        return new ChatLinkRelation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public ChatLinkRelation rename(Name name) {
        return new ChatLinkRelation(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public ChatLinkRelation rename(Table<?> name) {
        return new ChatLinkRelation(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<Long, UUID> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Long, ? super UUID, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Long, ? super UUID, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
