/*
 * This file is generated by jOOQ.
 */

package edu.java.domain.jooq.tables;

import edu.java.domain.jooq.DefaultSchema;
import edu.java.domain.jooq.Keys;
import edu.java.domain.jooq.tables.records.QuestionsRecord;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Questions extends TableImpl<QuestionsRecord> {

    /**
     * The reference instance of <code>QUESTIONS</code>
     */
    public static final Questions QUESTIONS = new Questions();
    private static final long serialVersionUID = 1L;
    /**
     * The column <code>QUESTIONS.QUESTION_ID</code>.
     */
    public final TableField<QuestionsRecord, Integer> QUESTION_ID =
        createField(DSL.name("QUESTION_ID"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");
    /**
     * The column <code>QUESTIONS.LINK_ID</code>.
     */
    public final TableField<QuestionsRecord, UUID> LINK_ID =
        createField(DSL.name("LINK_ID"), SQLDataType.UUID, this, "");
    /**
     * The column <code>QUESTIONS.ANSWER_COUNT</code>.
     */
    public final TableField<QuestionsRecord, Integer> ANSWER_COUNT =
        createField(DSL.name("ANSWER_COUNT"), SQLDataType.INTEGER.nullable(false), this, "");
    private transient Links _links;

    private Questions(Name alias, Table<QuestionsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Questions(Name alias, Table<QuestionsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>QUESTIONS</code> table reference
     */
    public Questions(String alias) {
        this(DSL.name(alias), QUESTIONS);
    }

    /**
     * Create an aliased <code>QUESTIONS</code> table reference
     */
    public Questions(Name alias) {
        this(alias, QUESTIONS);
    }

    /**
     * Create a <code>QUESTIONS</code> table reference
     */
    public Questions() {
        this(DSL.name("QUESTIONS"), null);
    }

    public <O extends Record> Questions(Table<O> child, ForeignKey<O, QuestionsRecord> key) {
        super(child, key, QUESTIONS);
    }

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<QuestionsRecord> getRecordType() {
        return QuestionsRecord.class;
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public Identity<QuestionsRecord, Integer> getIdentity() {
        return (Identity<QuestionsRecord, Integer>) super.getIdentity();
    }

    @Override
    @NotNull
    public UniqueKey<QuestionsRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_3B;
    }

    @Override
    @NotNull
    public List<UniqueKey<QuestionsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.CONSTRAINT_3BD);
    }

    @Override
    @NotNull
    public List<ForeignKey<QuestionsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_3BDD);
    }

    /**
     * Get the implicit join path to the <code>PUBLIC.LINKS</code> table.
     */
    public Links links() {
        if (_links == null) {
            _links = new Links(this, Keys.CONSTRAINT_3BDD);
        }

        return _links;
    }

    @Override
    @NotNull
    public Questions as(String alias) {
        return new Questions(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public Questions as(Name alias) {
        return new Questions(alias, this);
    }

    @Override
    @NotNull
    public Questions as(Table<?> alias) {
        return new Questions(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Questions rename(String name) {
        return new Questions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Questions rename(Name name) {
        return new Questions(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Questions rename(Table<?> name) {
        return new Questions(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row3<Integer, UUID, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super Integer, ? super UUID, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(
        Class<U> toType,
        Function3<? super Integer, ? super UUID, ? super Integer, ? extends U> from
    ) {
        return convertFrom(toType, Records.mapping(from));
    }
}
