/*
 * This file is generated by jOOQ.
 */

package edu.java.domain.jooq.tables.pojos;

import jakarta.validation.constraints.Size;
import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.UUID;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Links implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID linkId;
    private String link;
    private OffsetDateTime lastUpdate;
    private OffsetDateTime lastCheck;

    public Links() {
    }

    public Links(Links value) {
        this.linkId = value.linkId;
        this.link = value.link;
        this.lastUpdate = value.lastUpdate;
        this.lastCheck = value.lastCheck;
    }

    @ConstructorProperties({"linkId", "link", "lastUpdate", "lastCheck"})
    public Links(
        @NotNull UUID linkId,
        @Nullable String link,
        @NotNull OffsetDateTime lastUpdate,
        @NotNull OffsetDateTime lastCheck
    ) {
        this.linkId = linkId;
        this.link = link;
        this.lastUpdate = lastUpdate;
        this.lastCheck = lastCheck;
    }

    /**
     * Getter for <code>LINKS.LINK_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public UUID getLinkId() {
        return this.linkId;
    }

    /**
     * Setter for <code>LINKS.LINK_ID</code>.
     */
    public void setLinkId(@NotNull UUID linkId) {
        this.linkId = linkId;
    }

    /**
     * Getter for <code>LINKS.LINK</code>.
     */
    @Size(max = 1000000000)
    @Nullable
    public String getLink() {
        return this.link;
    }

    /**
     * Setter for <code>LINKS.LINK</code>.
     */
    public void setLink(@Nullable String link) {
        this.link = link;
    }

    /**
     * Getter for <code>LINKS.LAST_UPDATE</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public OffsetDateTime getLastUpdate() {
        return this.lastUpdate;
    }

    /**
     * Setter for <code>LINKS.LAST_UPDATE</code>.
     */
    public void setLastUpdate(@NotNull OffsetDateTime lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    /**
     * Getter for <code>LINKS.LAST_CHECK</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public OffsetDateTime getLastCheck() {
        return this.lastCheck;
    }

    /**
     * Setter for <code>LINKS.LAST_CHECK</code>.
     */
    public void setLastCheck(@NotNull OffsetDateTime lastCheck) {
        this.lastCheck = lastCheck;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Links other = (Links) obj;
        if (this.linkId == null) {
            if (other.linkId != null) {
                return false;
            }
        } else if (!this.linkId.equals(other.linkId)) {
            return false;
        }
        if (this.link == null) {
            if (other.link != null) {
                return false;
            }
        } else if (!this.link.equals(other.link)) {
            return false;
        }
        if (this.lastUpdate == null) {
            if (other.lastUpdate != null) {
                return false;
            }
        } else if (!this.lastUpdate.equals(other.lastUpdate)) {
            return false;
        }
        if (this.lastCheck == null) {
            if (other.lastCheck != null) {
                return false;
            }
        } else if (!this.lastCheck.equals(other.lastCheck)) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.linkId == null) ? 0 : this.linkId.hashCode());
        result = prime * result + ((this.link == null) ? 0 : this.link.hashCode());
        result = prime * result + ((this.lastUpdate == null) ? 0 : this.lastUpdate.hashCode());
        result = prime * result + ((this.lastCheck == null) ? 0 : this.lastCheck.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Links (");

        sb.append(linkId);
        sb.append(", ").append(link);
        sb.append(", ").append(lastUpdate);
        sb.append(", ").append(lastCheck);

        sb.append(")");
        return sb.toString();
    }
}
