FROM openjdk:21
LABEL authors="digital-nishtyak"

ENV TELEGRAM_API_KEY=${TELEGRAM_API_KEY} \
    SCRAPPER_URL=${SCRAPPER_URL} \
    KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS} \
    SERVER_PORT=${SERVER_POST} \
    MANAGEMENT_PORT=${MANAGEMENT_PORT}

COPY ./target/bot.jar bot.jar

ENTRYPOINT ["java","-jar","/bot.jar"]
