/*
 * This file is generated by jOOQ.
 */

package edu.java.domain.jooq;

import edu.java.domain.jooq.tables.ChatLinkRelation;
import edu.java.domain.jooq.tables.Chats;
import edu.java.domain.jooq.tables.Links;
import edu.java.domain.jooq.tables.Questions;
import edu.java.domain.jooq.tables.Repositories;
import edu.java.domain.jooq.tables.records.ChatLinkRelationRecord;
import edu.java.domain.jooq.tables.records.ChatsRecord;
import edu.java.domain.jooq.tables.records.LinksRecord;
import edu.java.domain.jooq.tables.records.QuestionsRecord;
import edu.java.domain.jooq.tables.records.RepositoriesRecord;
import javax.annotation.processing.Generated;
import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChatLinkRelationRecord> CONSTRAINT_B =
        Internal.createUniqueKey(ChatLinkRelation.CHAT_LINK_RELATION,
            DSL.name("CONSTRAINT_B"),
            new TableField[] {ChatLinkRelation.CHAT_LINK_RELATION.CHAT_ID, ChatLinkRelation.CHAT_LINK_RELATION.LINK_ID},
            true
        );
    public static final UniqueKey<ChatsRecord> CONSTRAINT_3 = Internal.createUniqueKey(Chats.CHATS,
        DSL.name("CONSTRAINT_3"),
        new TableField[] {Chats.CHATS.TELEGRAM_CHAT_ID},
        true
    );
    public static final UniqueKey<ChatsRecord> CONSTRAINT_3D = Internal.createUniqueKey(Chats.CHATS,
        DSL.name("CONSTRAINT_3D"),
        new TableField[] {Chats.CHATS.TELEGRAM_CHAT_ID},
        true
    );
    public static final UniqueKey<LinksRecord> CONSTRAINT_4 =
        Internal.createUniqueKey(Links.LINKS, DSL.name("CONSTRAINT_4"), new TableField[] {Links.LINKS.LINK_ID}, true);
    public static final UniqueKey<QuestionsRecord> CONSTRAINT_3B = Internal.createUniqueKey(Questions.QUESTIONS,
        DSL.name("CONSTRAINT_3B"),
        new TableField[] {Questions.QUESTIONS.QUESTION_ID},
        true
    );
    public static final UniqueKey<QuestionsRecord> CONSTRAINT_3BD = Internal.createUniqueKey(Questions.QUESTIONS,
        DSL.name("CONSTRAINT_3BD"),
        new TableField[] {Questions.QUESTIONS.LINK_ID},
        true
    );
    public static final UniqueKey<RepositoriesRecord> CONSTRAINT_8 = Internal.createUniqueKey(Repositories.REPOSITORIES,
        DSL.name("CONSTRAINT_8"),
        new TableField[] {Repositories.REPOSITORIES.REPOSITORY_ID},
        true
    );
    public static final UniqueKey<RepositoriesRecord> CONSTRAINT_81 =
        Internal.createUniqueKey(Repositories.REPOSITORIES,
            DSL.name("CONSTRAINT_81"),
            new TableField[] {Repositories.REPOSITORIES.LINK_ID},
            true
        );

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ChatLinkRelationRecord, ChatsRecord> CONSTRAINT_B8 = Internal.createForeignKey(
        ChatLinkRelation.CHAT_LINK_RELATION,
        DSL.name("CONSTRAINT_B8"),
        new TableField[] {ChatLinkRelation.CHAT_LINK_RELATION.CHAT_ID},
        Keys.CONSTRAINT_3,
        new TableField[] {Chats.CHATS.TELEGRAM_CHAT_ID},
        true
    );
    public static final ForeignKey<ChatLinkRelationRecord, LinksRecord> CONSTRAINT_B80 = Internal.createForeignKey(
        ChatLinkRelation.CHAT_LINK_RELATION,
        DSL.name("CONSTRAINT_B80"),
        new TableField[] {ChatLinkRelation.CHAT_LINK_RELATION.LINK_ID},
        Keys.CONSTRAINT_4,
        new TableField[] {Links.LINKS.LINK_ID},
        true
    );
    public static final ForeignKey<QuestionsRecord, LinksRecord> CONSTRAINT_3BDD =
        Internal.createForeignKey(Questions.QUESTIONS,
            DSL.name("CONSTRAINT_3BDD"),
            new TableField[] {Questions.QUESTIONS.LINK_ID},
            Keys.CONSTRAINT_4,
            new TableField[] {Links.LINKS.LINK_ID},
            true
        );
    public static final ForeignKey<RepositoriesRecord, LinksRecord> CONSTRAINT_81B = Internal.createForeignKey(
        Repositories.REPOSITORIES,
        DSL.name("CONSTRAINT_81B"),
        new TableField[] {Repositories.REPOSITORIES.LINK_ID},
        Keys.CONSTRAINT_4,
        new TableField[] {Links.LINKS.LINK_ID},
        true
    );
}
