/*
 * This file is generated by jOOQ.
 */

package edu.java.domain.jooq;

import edu.java.domain.jooq.tables.ChatLinkRelation;
import edu.java.domain.jooq.tables.Chats;
import edu.java.domain.jooq.tables.Links;
import edu.java.domain.jooq.tables.Questions;
import edu.java.domain.jooq.tables.Repositories;
import javax.annotation.processing.Generated;

/**
 * Convenience access to all tables in the default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Tables {

    /**
     * The table <code>CHAT_LINK_RELATION</code>.
     */
    public static final ChatLinkRelation CHAT_LINK_RELATION = ChatLinkRelation.CHAT_LINK_RELATION;

    /**
     * The table <code>CHATS</code>.
     */
    public static final Chats CHATS = Chats.CHATS;

    /**
     * The table <code>LINKS</code>.
     */
    public static final Links LINKS = Links.LINKS;

    /**
     * The table <code>QUESTIONS</code>.
     */
    public static final Questions QUESTIONS = Questions.QUESTIONS;

    /**
     * The table <code>REPOSITORIES</code>.
     */
    public static final Repositories REPOSITORIES = Repositories.REPOSITORIES;
}
